### ISSUE TITLE
لینک کردن سوالات

### ISSUE THREAD

**Issue by MEgooneh** [shaazzz/GTOI#9]
اگر میشه سوالات هر تاپیک رو لینک کنید به همون باتن سوالات تو بالای اون صفحه . مثلا اگه بخش 2 قسمت 4 هستیم با زدن دکمه ی سوالات لازم به پیدا کردن بخش نباشه .

**Comment by hkalbasi** [comment]
باید درست شده باشه. ولی اگه خراب بود بگو. ممکنه روی مرورگر های قدیمی مشکل داشته باشه.
